In [1]:
import tensorflow as tf
print(tf.__version__)
import numpy as np
import matplotlib.pyplot as plt

2.12.0


In [2]:
a = np.array([[1, 2, 3], [4, 5, 6],[-2, 7, 10], [-4, -15, 60],[111, 21, -3], [455, 52, -6],[-11, 232, -123], [-94, -35, -6]])
#X = tf.constant([-7.0, -4.0, -1.0 , 2.0, 5.0, 8.0, 11.0, 14.0])
X=tf.constant(a)
y = tf.constant([3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0])
#plt.scatter(X,y);

In [3]:

tf.random.set_seed(442)

# 1. Create a module using the sequential API
model = tf.keras.Sequential([
  tf.keras.layers.Dense(50, input_shape=[3]), 
  tf.keras.layers.Dense(100), 
  tf.keras.layers.Dense(50), 
  tf.keras.layers.Dense(200),
  tf.keras.layers.Dense(200),
  tf.keras.layers.Dense(150),                             
  tf.keras.layers.Dense(1)
])
# 2. Compile the model
model.compile(loss = tf.keras.losses.mse,
              optimizer =tf.keras.optimizers.Adam(),
              metrics= ['mse'])

#Fit the model
model.fit(tf.expand_dims(X, axis=-1), y, epochs=100);

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 1167.8754 - mse: 1167.8754
Epoch 2/100
1/1 [==============================] - 0s 11ms/step - loss: 3466.9766 - mse: 3466.9766
Epoch 3/100
1/1 [==============================] - 0s 15ms/step - loss: 2516.6433 - mse: 2516.6433
Epoch 4/100
1/1 [==============================] - 0s 18ms/step - loss: 1665.4648 - mse: 1665.4648
Epoch 5/100
1/1 [==============================] - 0s 18ms/step - loss: 269.5838 - mse: 269.5838
Epoch 6/100
1/1 [==============================] - 0s 20ms/step - loss: 455.0841 - mse: 455.0841
Epoch 7/100
1/1 [==============================] - 0s 17ms/step - loss: 1022.5587 - mse: 1022.5587
Epoch 8/100
1/1 [==============================] - 0s 21ms/step - loss: 978.7782 - mse: 978.7782
Epoch 9/100
1/1 [==============================] - 0s 19ms/step - loss: 627.9949 - mse: 627.9949
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 391.5052 - mse: 391.5052
Epoch 11/100
1/1 [===

In [4]:
model.predict(X)

1/1 [==============================] - 0s 159ms/step


array([[ 3.0817227],
       [ 3.6019514],
       [ 3.9448283],
       [ 4.5680685],
       [ 6.2919426],
       [14.36675  ],
       [18.893063 ],
       [-2.5866024]], dtype=float32)

In [5]:
X,y

(<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[   1,    2,    3],
        [   4,    5,    6],
        [  -2,    7,   10],
        [  -4,  -15,   60],
        [ 111,   21,   -3],
        [ 455,   52,   -6],
        [ -11,  232, -123],
        [ -94,  -35,   -6]])>,
 <tf.Tensor: shape=(8,), dtype=float32, numpy=array([ 3.,  6.,  9., 12., 15., 18., 21., 24.], dtype=float32)>)